### PR TITLE
html js and css pages added

### PR DESCRIPTION
**Pull request by daniella-mcnair**

### CODE REVIEW

**Comment by daniella-mcnair** [comment]
This is what it looks like so far. I have placed items on the overview html as placeholders

image
image

**Comment by daniella-mcnair** [comment]
What it looks like currently
image
image

**Comment by daniella-mcnair** [comment]
I added mock data to the js file for the user and created a mock function to render the function

**Comment by daniella-mcnair** [comment]
image

Also I set up the grid kind of close to this

**Review by DamitryDong — APPROVED** [review]
Looks Good! Since we have nothing anyways, I think we approve it and if we run into any issues in as we code, we just push for another pull request after notifying others

**Review by jaylenxr — APPROVED** [review]
Everything looks great so far! Will make changes as needed if any we run into any issues

**Pull request merged**
